import React, { useEffect, useState } from 'react';
import { api, formatDate } from '../api';
import { useAuth } from '../auth';
import Modal from '../components/Modal';
import StatusBadge from '../components/StatusBadge';
import EmptyState from '../components/EmptyState';

export default function LeavePage() {
  const { user } = useAuth();
  const [types, setTypes] = useState([]); const [requests, setRequests] = useState([]); const [entitlements, setEntitlements] = useState([]);
  const [modal, setModal] = useState(false); const [form, setForm] = useState({ leave_type_id: '', start_date: '', end_date: '', reason: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const canReview = user.role !== 'EMPLOYEE';
  async function load() { try { const [typeData, requestData, entitlementData] = await Promise.all([api('/api/leave/types'), api('/api/leave/requests'), api('/api/leave/entitlements')]); setTypes(typeData); setRequests(requestData); setEntitlements(entitlementData); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, []);
  async function apply(event) { event.preventDefault(); setSaving(true); setError(''); try { await api('/api/leave/requests', { method: 'POST', body: JSON.stringify({ ...form, leave_type_id: Number(form.leave_type_id) }) }); setModal(false); setForm({ leave_type_id: '', start_date: '', end_date: '', reason: '' }); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function review(id, decision) { const remark = window.prompt(`${decision === 'approve' ? 'Approve' : 'Reject'} request. Optional remark:`) ?? ''; if (remark === null) return; try { await api(`/api/leave/requests/${id}/${decision}`, { method: 'POST', body: JSON.stringify({ remark }) }); await load(); } catch (err) { setError(err.message); } }
  return <div className="page">
    <div className="page-heading action-heading"><div><span className="eyebrow">LEAVE MANAGEMENT</span><h1>Leave requests and balances</h1><p>Apply leave, monitor balances and complete approvals from one clear workflow.</p></div><button className="button primary" onClick={() => { setError(''); setModal(true); }}>+ Apply leave</button></div>
    {error && <div className="alert alert-danger">{error}</div>}
    <section className="content-card"><div className="card-heading"><div><h2>Leave entitlement</h2><p>Current year balances shown after approved applications.</p></div></div>{entitlements.length === 0 ? <EmptyState title="No leave entitlement" /> : <div className="balance-grid">{entitlements.map((item) => <article className="balance-card" key={item.id}><span>{item.employee_name ? `${item.employee_name} · ` : ''}{item.leave_type}</span><strong>{Number(item.balance_days).toFixed(1)} <small>days</small></strong><p>{Number(item.used_days).toFixed(1)} used of {Number(item.entitled_days).toFixed(1)}</p></article>)}</div>}</section>
    <section className="content-card"><div className="card-heading"><div><h2>{canReview ? 'Leave review queue' : 'My leave applications'}</h2><p>{canReview ? 'Review all leave applications in the organisation.' : 'Track the current status of your applications.'}</p></div></div>{requests.length === 0 ? <EmptyState title="No leave applications" note="Create your first application with the button above." /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Leave type</th><th>Period</th><th>Days</th><th>Status</th><th>Remark</th>{canReview && <th></th>}</tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><b>{request.employee_name}</b></td><td>{request.leave_type}</td><td>{formatDate(request.start_date)} – {formatDate(request.end_date)}</td><td>{request.requested_days}</td><td><StatusBadge value={request.status} /></td><td>{request.reviewer_remark || '—'}</td>{canReview && <td className="row-actions">{request.status === 'PENDING' && <><button className="text-button success-text" onClick={() => review(request.id, 'approve')}>Approve</button><button className="text-button danger-text" onClick={() => review(request.id, 'reject')}>Reject</button></>}</td>}</tr>)}</tbody></table></div>}</section>
    {modal && <Modal title="New leave application" onClose={() => setModal(false)}><form className="form-stack" onSubmit={apply}><label>Leave type<select required value={form.leave_type_id} onChange={(event) => setForm({ ...form, leave_type_id: event.target.value })}><option value="">Select leave type</option>{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><div className="form-grid two"><label>Start date<input required type="date" value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} /></label><label>End date<input required type="date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} /></label></div><label>Reason<textarea rows="4" value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} placeholder="Provide a concise reason for the leave." /></label>{error && <div className="alert alert-danger">{error}</div>}<div className="form-actions"><button className="button ghost" type="button" onClick={() => setModal(false)}>Cancel</button><button className="button primary" disabled={saving}>{saving ? 'Submitting…' : 'Submit application'}</button></div></form></Modal>}
  </div>;
}
