import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, formatMoney, formatDate } from '../api';
import { useAuth } from '../auth';
import EmptyState from '../components/EmptyState';

export default function EmployeesPage() {
  const { user } = useAuth(); const navigate = useNavigate();
  const [employees, setEmployees] = useState([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [showArchived, setShowArchived] = useState(false);
  const canEdit = user.role !== 'EMPLOYEE'; const canArchive = user.role === 'ADMIN';
  async function load() { try { setEmployees(await api(`/api/employees${showArchived ? '?archived=true' : ''}`)); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, [showArchived]);
  const filtered = useMemo(() => employees.filter((employee) => `${employee.first_name} ${employee.middle_name || ''} ${employee.last_name} ${employee.employee_code} ${employee.work_email || ''} ${employee.job_title || ''}`.toLowerCase().includes(search.toLowerCase())), [employees, search]);
  async function archive(employee) { if (!window.confirm(`Archive ${employee.first_name} ${employee.last_name}?`)) return; try { await api(`/api/employees/${employee.id}/archive`, { method: 'POST' }); await load(); } catch (err) { setError(err.message); } }
  return <div className="page"><div className="page-heading action-heading"><div><span className="eyebrow">EMPLOYEE MANAGEMENT</span><h1>Employee centre</h1><p>Full employee records with quick entry, personal details, placement, salary, family, contacts, health, directory privacy, access and configurable fields.</p></div>{canEdit && <Link className="button primary" to="/employees/new">+ New employee</Link>}</div>{error && <div className="alert alert-danger">{error}</div>}<section className="content-card"><div className="toolbar"><div className="search-input"><span>⌕</span><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search employee name, code, email or position" /></div>{canArchive && <label className="checkbox-row"><input type="checkbox" checked={showArchived} onChange={(event)=>setShowArchived(event.target.checked)} /> Include archived</label>}<span className="count-label">{filtered.length} employee{filtered.length === 1 ? '' : 's'}</span></div>{filtered.length === 0 ? <EmptyState title="No employee records found" note="Create the first employee through Quick Entry." /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Placement</th><th>Employment</th><th>Account</th><th>Salary</th><th></th></tr></thead><tbody>{filtered.map((employee)=><tr key={employee.id} onDoubleClick={()=>navigate(`/employees/${employee.id}`)}><td><div className="person-cell"><span className="avatar">{employee.first_name?.slice(0,1)}{employee.last_name?.slice(0,1)}</span><div><b>{employee.first_name} {employee.middle_name ? `${employee.middle_name} ` : ''}{employee.last_name}</b><small>{employee.employee_code} · {employee.work_email || 'No work email'}</small></div></div></td><td><b>{employee.job_title || 'Not set'}</b><br/><span className="muted">{employee.department_name || 'No department'}{employee.manager_name ? ` · ${employee.manager_name}` : ''}</span></td><td>{employee.employment_type || '—'}<br/><span className="muted">Joined {formatDate(employee.hire_date)}</span></td><td>{employee.user_role ? <span className="status status-approved">{employee.user_role}</span> : <span className="muted">No account</span>}</td><td>{formatMoney(employee.basic_salary)}</td><td className="row-actions"><Link className="text-button" to={`/employees/${employee.id}`}>Open dossier</Link>{canArchive && employee.active && <button className="text-button danger-text" onClick={()=>archive(employee)}>Archive</button>}</td></tr>)}</tbody></table></div>}</section><div className="module-shortcuts"><Link to="/people-records">Employee history register →</Link><Link to="/access">Custom roles, HR roles & web accounts →</Link></div></div>;
}
